# Generated by Django 3.1.1 on 2020-09-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=240)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('total_votes', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
